#!/bin/bash

ENV_FILE="./.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "Arquivo .env não encontrado!"
  exit 1
fi

export $(grep -v '^#' $ENV_FILE | xargs)

echo "Variáveis de ambiente carregadas:"
printenv | grep -f $ENV_FILE
