spring:
  application:
    name: account-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/amsdb
    username: postgres
    password: developer2024
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: amsschema
        ddl-auto: validate
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true